name: Build LibrePods Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.6.3
        host: windows
        target: desktop
        arch: win64_msvc2019_64
        modules: qtconnectivity qtmultimedia
        cache: true

    - name: Install vcpkg
      shell: cmd
      run: |
        git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
        cd C:\vcpkg
        bootstrap-vcpkg.bat

    - name: Install OpenSSL
      shell: cmd
      run: |
        C:\vcpkg\vcpkg install openssl:x64-windows

    - name: Configure CMake
      shell: cmd
      run: |
        cd windows
        mkdir build
        cd build
        cmake .. ^
        -G "Visual Studio 17 2022" ^
        -A x64 ^
        -DCMAKE_SYSTEM_VERSION=10.0 ^
        -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake ^
        -DCMAKE_PREFIX_PATH="%QT_ROOT_DIR%" ^
        -DOPENSSL_ROOT_DIR=C:/vcpkg/installed/x64-windows

    - name: Build
      shell: cmd
      run: |
        cd windows\build
        cmake --build . --config Release --parallel 4

    - name: Find exe
      shell: cmd
      run: |
        dir /s librepods-windows.exe

    - name: Deploy Qt
      shell: cmd
      run: |
        for /r windows\build %%i in (librepods-windows.exe) do (
          cd /d %%~dpi
          "%QT_ROOT_DIR%\bin\windeployqt.exe" ^
          --release ^
          --compiler-runtime ^
          --qmldir "%GITHUB_WORKSPACE%\windows" ^
          librepods-windows.exe
        )

    - name: Copy OpenSSL DLL
      shell: cmd
      run: |
        for /r windows\build %%i in (librepods-windows.exe) do (
          copy C:\vcpkg\installed\x64-windows\bin\libssl-*.dll %%~dpi
          copy C:\vcpkg\installed\x64-windows\bin\libcrypto-*.dll %%~dpi
        )

    - name: Verify
      shell: cmd
      run: |
        dir /s windows\build\*.exe
        dir /s windows\build\*.dll

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: LibrePods-Windows
        path: windows/build/**
