name: Build LibrePods Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:

      # 拉取源码
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive


      # 安装固定版本 vcpkg
      - name: Setup vcpkg
        shell: cmd
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          cd C:\vcpkg
          git checkout 2024.09.30
          bootstrap-vcpkg.bat


      # 安装依赖
      # 使用 Qt6 + OpenSSL
      - name: Install dependencies
        shell: cmd
        run: |
          C:\vcpkg\vcpkg install ^
          qtbase[core,gui,network,widgets,opengl]:x64-windows ^
          qtconnectivity:x64-windows ^
          qtmultimedia:x64-windows ^
          qtdeclarative:x64-windows ^
          openssl:x64-windows ^
          --clean-after-build


      # CMake配置
      - name: Configure CMake
        shell: cmd
        run: |
          cd windows
          mkdir build
          cd build

          cmake .. ^
          -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake ^
          -DCMAKE_BUILD_TYPE=Release


      # 编译
      - name: Build
        shell: cmd
        run: |
          cd windows/build
          cmake --build . --config Release


      # 上传exe
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: librepods-windows-release
          path: |
            windows/build/Release/*.exe
            windows/build/Release/*.dll
