name: Build LibrePods Windows

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2022

    timeout-minutes: 360

    steps:

    # 拉取源码
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive


    # 安装 Qt6 官方预编译版本
    - name: Install Qt6
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.6.3
        host: windows
        target: desktop
        arch: win64_msvc2019_64
        modules: >
          qtconnectivity
          qtmultimedia
          qtdeclarative


    # 安装 vcpkg
    - name: Install vcpkg
      shell: cmd
      run: |
        git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
        cd C:\vcpkg
        git checkout 2024.09.30
        bootstrap-vcpkg.bat


    # 只安装OpenSSL
    - name: Install OpenSSL
      shell: cmd
      run: |
        C:\vcpkg\vcpkg install openssl:x64-windows


    # 配置CMake
    - name: Configure CMake
      shell: cmd
      run: |

        cd windows

        mkdir build

        cd build


        cmake .. ^
        -DCMAKE_BUILD_TYPE=Release ^
        -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake ^
        -DCMAKE_PREFIX_PATH=%Qt6_DIR%


    # 编译
    - name: Build
      shell: cmd
      run: |

        cd windows\build

        cmake --build . --config Release


    # 自动部署Qt
    - name: Deploy Qt Runtime
      shell: cmd
      run: |

        cd windows\build\Release

        "%Qt6_DIR%\bin\windeployqt.exe" ^
        --release ^
        --compiler-runtime ^
        --qmldir ..\..\ ^
        librepods-windows.exe


    # 检查文件
    - name: List files
      shell: cmd
      run: |

        dir windows\build\Release

        dir windows\build\Release\platforms


    # 打包
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:

        name: LibrePods-Windows

        path: |
          windows/build/Release/**
